# Generated by Django 5.1.1 on 2025-03-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now=True)),
                ('state1', models.CharField(max_length=50)),
                ('state2', models.BooleanField()),
            ],
        ),
    ]
