# Generated by Django 5.1.1 on 2025-03-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='data',
            new_name='date',
        ),
    ]
